# Github Actions workflow file for the communication
name: Communication

on:
    push:
        branches:
            - dev
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/vdobrovolskyi/watchtogether.fun
                      echo "🔄 Cтягиваем код с github"
                      echo "🗑 Очищаем следы прошлых запусков, если имеются"
                      if [ -d "streaming-communication" ]; then
                          rm -rf streaming-communication
                      fi
                      git clone git@github.com:VladyslavDobrovolskyi/streaming-communication.git
                      cd streaming-communication
                      git checkout dev
                      git pull
                      rm -rf .git

                      echo "🔄 Остановка и пересборка контейнера"
                      echo "🛑 Проверка наличия контейнера streaming-communication"
                      if [ $(docker ps -q -f name=streaming-communication) ]; then
                          echo "🛑 Остановка контейнера streaming-communication"
                          docker stop streaming-communication || true
                          docker rm streaming-communication || true
                      fi

                      echo "🗑 Удаление предыдущего образа streaming-communication, если он существует"
                      if [ $(docker images -q streaming-communication) ]; then
                          docker rmi streaming-communication || true
                      fi

                      echo "🛠 Пересборка контейнера streaming-communication без кэша"
                      docker build -t streaming-communication .

                      echo "🔍 Проверка наличия сети watchtogether-network"
                      if [ ! $(docker network ls -q -f name=watchtogether-network) ]; then
                          echo "🌐 Сеть watchtogether-network не найдена, создаем сеть"
                          docker network create watchtogether-network
                      fi

                      echo "🚀 Запуск контейнера streaming-communication"
                      docker run -d --name streaming-communication \
                        --network watchtogether-network \
                        --restart always \
                        -p 20999:20999 \
                        streaming-communication

                      echo "🔍 Проверка, что контейнер streaming-communication поднялся"
                      if [ $(docker ps -q -f name=streaming-communication) ]; then
                          echo "✅ Контейнер streaming-communication успешно запущен"
                      else
                          echo "❌ Контейнер streaming-communication не запущен"
                          exit 1
                      fi

                      cd /home/vdobrovolskyi/watchtogether.fun

                       echo "🔍 Проверка наличия контейнеров postgres и nginx"
                      if [ ! $(docker ps -q -f name=postgres) ]; then
                          echo "❌ Контейнер postgres не найден, запускаем docker-compose up"
                          docker-compose up -d postgres
                      fi
                      if [ ! $(docker ps -q -f name=nginx) ]; then
                          echo "❌ Контейнер nginx не найден, запускаем docker-compose up"
                          docker-compose up -d nginx
                      fi



                      echo "🗑 Очищаем пространство"
                      if [ -d "streaming-communication" ]; then
                          rm -rf streaming-communication
                      fi

                      echo "✅ Деплой завершен успешно!"
